import { useEffect, useMemo, useRef, useState } from 'react';
import { Bot, ChevronLeft, ChevronRight, MessageSquare, PanelRight, Search, Send, Sparkles, UserRound } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { base44 } from '@/api/base44Client';
import { AiUnavailable } from '@/components/agency/AgencyUI';
import { isApiConfigurationError } from '@/lib/channel-analysis';
import { useClients } from '@/lib/agency-data';

const SYSTEM_PROMPT = 'You are an expert content strategist specializing in personal-brand growth on YouTube and social media. You help ideate video titles, thumbnail concepts, content angles, hooks, and growth strategies. You remember everything in this thread and build on previous insights. When given a YouTube URL, analyze its content strategy and extract learnings.';
const titleFrom = text => text.trim().replace(/\s+/g,' ').slice(0,54) || 'New idea';
export default function Ideation() {
  const clients = useClients(); const [threads,setThreads]=useState([]); const [activeId,setActiveId]=useState(null); const [messages,setMessages]=useState([]); const [input,setInput]=useState(''); const [search,setSearch]=useState(''); const [panel,setPanel]=useState(true); const [busy,setBusy]=useState(false); const [apiMissing,setApiMissing]=useState(false); const [error,setError]=useState(''); const endRef=useRef(null);
  const active=threads.find(t=>t.id===activeId); const filtered=threads.filter(t=>t.title.toLowerCase().includes(search.toLowerCase()));
  async function loadThreads(){const rows=await base44.entities.IdeationThread.list('-createdAt',200);setThreads(rows);if(rows.length&&!activeId)setActiveId(rows[0].id);}
  useEffect(()=>{loadThreads().catch(err=>setError(err.message));},[]);
  useEffect(()=>{if(!activeId){setMessages([]);return;} base44.entities.IdeationMessage.filter({thread:activeId},'timestamp',500).then(setMessages).catch(err=>setError(err.message));},[activeId]);
  useEffect(()=>endRef.current?.scrollIntoView({behavior:'smooth'}),[messages,busy]);
  const clientContext=useMemo(()=>(clients.data||[]).map(c=>({id:c.id,name:c.name,summary:c.channelSummary,offers:c.offers,strategy:c.contentStrategy,plan:c.planType,status:c.status})),[clients.data]);
  async function send(){const content=input.trim();if(!content||busy)return;setBusy(true);setInput('');setError('');setApiMissing(false);let threadId=activeId;try{
      if(!threadId){const created=await base44.entities.IdeationThread.create({title:titleFrom(content),createdAt:new Date().toISOString()});threadId=created.id;setActiveId(threadId);setThreads(current=>[created,...current]);}
      const userMessage=await base44.entities.IdeationMessage.create({thread:threadId,role:'user',content,timestamp:new Date().toISOString()});setMessages(current=>[...current,userMessage]);
      const history=await base44.entities.IdeationMessage.filter({thread:threadId},'timestamp',500);
      let globalVideoKnowledge='';try{const entries=await base44.entities.KnowledgeEntry.filter({scope:'VIDEO_GLOBAL'},'timestamp',500);globalVideoKnowledge=entries.map(entry=>entry.learnedPrinciple).join('\n');}catch{/* training may not exist yet */}
      const transcript=history.map(m=>`${m.role.toUpperCase()}: ${m.content}`).join('\n\n');
      let boundedHistory=transcript;
      if(transcript.length>60000){const recent=history.slice(-20).map(m=>`${m.role.toUpperCase()}: ${m.content}`).join('\n\n');const older=history.slice(0,-20).map(m=>`${m.role.toUpperCase()}: ${m.content}`).join('\n\n');const summary=await base44.functions.invoke('summarizeAgencyHistory',{history:older});boundedHistory=`OLDER HISTORY SUMMARY:\n${summary.data.result}\n\nRECENT MESSAGES:\n${recent}`;}
      const response=await base44.functions.invoke('generateAgencyIdeas',{message:content,history:boundedHistory.slice(-24000),knowledge:globalVideoKnowledge.slice(0,6000),clients:JSON.stringify(clientContext).slice(0,9000)});
      const assistantMessage=await base44.entities.IdeationMessage.create({thread:threadId,role:'assistant',content:String(response.data.result),timestamp:new Date().toISOString()});setMessages(current=>[...current,assistantMessage]);
    }catch(err){if(isApiConfigurationError(err))setApiMissing(true);else setError(err?.message||'The message could not be sent.');}finally{setBusy(false);}}
  const onKeyDown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send();}};
  async function tagClient(clientId){if(!active)return;const updated=await base44.entities.IdeationThread.update(active.id,{client:clientId||null});setThreads(rows=>rows.map(row=>row.id===active.id?{...row,...updated}:row));}
  const createNew=()=>{setActiveId(null);setMessages([]);setInput('');};
  return <section className="agency-enter -mb-16 -mt-8 flex min-h-[calc(100vh-72px)] gap-4 sm:-mt-12 lg:-mt-16">
    <div className="flex min-w-0 flex-1 flex-col"><header className={`flex h-16 items-center ${threads.length?'justify-between':'justify-end'}`}>{threads.length>0&&<div><h1 className="text-lg font-semibold text-agency-primary">{active?.title||'New idea'}</h1>{active?.client&&<p className="mt-0.5 text-xs text-agency-muted">{clients.data?.find(c=>c.id===active.client)?.name}</p>}</div>}<button onClick={()=>setPanel(v=>!v)} className="agency-icon-button flex h-9 w-9 items-center justify-center rounded-xl" aria-label="Toggle thread panel"><PanelRight className="h-4 w-4"/></button></header>
      <div className={`flex-1 overflow-y-auto agency-scrollbar ${messages.length?'py-6':'flex items-center justify-center'}`}>{!messages.length?<div className="mx-auto w-full max-w-2xl px-4 text-center"><div className="mx-auto mb-5 flex h-12 w-12 items-center justify-center rounded-2xl bg-[#64D2FF]/10 text-[#64D2FF]"><Sparkles/></div><h2 className="text-3xl font-semibold tracking-tight text-agency-primary">What should we create next?</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-agency-muted">Develop titles, hooks, thumbnails, content angles, and growth strategy with an AI that remembers the entire thread.</p></div>:<div className="mx-auto w-full max-w-3xl space-y-7 px-3 sm:px-6">{messages.map(message=><div key={message.id} className={`flex gap-3 ${message.role==='user'?'justify-end':''}`}>{message.role==='assistant'&&<span className="agency-chat-avatar ai"><Bot/></span>}<div className={`agency-message ${message.role}`}><ReactMarkdown>{message.content}</ReactMarkdown></div>{message.role==='user'&&<span className="agency-chat-avatar user"><UserRound/></span>}</div>)}{busy&&<div className="flex gap-3"><span className="agency-chat-avatar ai"><Bot/></span><div className="agency-message assistant"><span className="agency-thinking"><i/><i/><i/></span></div></div>}<div ref={endRef}/></div>}</div>
      <div className="mx-auto w-full max-w-3xl px-3 pb-6 sm:px-6">{apiMissing&&<div className="mb-3"><AiUnavailable compact/></div>}{error&&<p className="mb-3 rounded-xl bg-red-500/10 p-3 text-sm text-[#FF453A]">{error}</p>}<div className="agency-chat-input"><textarea value={input} onChange={e=>setInput(e.target.value)} onKeyDown={onKeyDown} rows={1} placeholder="Ask for a title, hook, thumbnail, or strategy…"/><button onClick={send} disabled={!input.trim()||busy} aria-label="Send message"><Send/></button></div><p className="mt-2 text-center text-[11px] text-agency-muted">Enter to send · Shift + Enter for a new line</p></div>
    </div>
    <aside className={`agency-thread-panel ${panel?'is-open':''}`}><div className="flex items-center justify-between"><h2 className="font-semibold text-agency-primary">Threads</h2><button onClick={()=>setPanel(false)} className="agency-icon-button flex h-8 w-8 items-center justify-center rounded-lg"><ChevronRight className="h-4 w-4"/></button></div><button onClick={createNew} className="agency-button-primary mt-4 w-full justify-center"><MessageSquare className="h-4 w-4"/>New thread</button><label className="agency-search mt-4"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search threads…"/></label><div className="mt-4 flex-1 space-y-1 overflow-y-auto agency-scrollbar">{filtered.map(thread=><button key={thread.id} onClick={()=>setActiveId(thread.id)} className={`agency-thread ${thread.id===activeId?'is-active':''}`}><span>{thread.title}</span>{thread.client&&<small>{clients.data?.find(c=>c.id===thread.client)?.name||'Client'}</small>}</button>)}</div>{active&&<label className="agency-field mt-4"><span>Tag this thread</span><select value={active.client||''} onChange={e=>tagClient(e.target.value)}><option value="">No client</option>{(clients.data||[]).map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>}</aside>{!panel&&threads.length>0&&<button className="agency-panel-tab" onClick={()=>setPanel(true)}><ChevronLeft/><span>Threads</span></button>}
  </section>;
}