import { useMemo } from 'react';
import { CheckCircle2, CircleDollarSign, TrendingUp, WalletCards } from 'lucide-react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ErrorState, LoadingState, PageHeader } from '@/components/agency/AgencyUI';
import { agencyKeys, labelize, money, shortDate, useClients, useEntityMutation, usePayments, useTeam } from '@/lib/agency-data';
import { buildMoneyModel } from '@/lib/finance';

const tooltipStyle = { background:'#1c1c1e', border:'1px solid rgba(255,255,255,.1)', borderRadius:12, color:'#f5f5f7' };
export default function MoneyPage() {
  const clients = useClients(); const payments = usePayments(); const team = useTeam(); const paymentMutation = useEntityMutation('Payment', agencyKeys.payments);
  const model = useMemo(() => {
    const clientRows = /** @type {any[]} */ (clients.data || []);
    const paymentRows = /** @type {any[]} */ (payments.data || []);
    const members = /** @type {any[]} */ (team.data || []);
    return buildMoneyModel(clientRows, paymentRows, members);
  }, [clients.data,payments.data,team.data]);
  if ([clients,payments,team].some(q=>q.isLoading)) return <LoadingState/>; if ([clients,payments,team].some(q=>q.isError)) return <ErrorState/>;
  const cards = [{label:'Total revenue',value:money(model.totalRevenue),sub:'Collected payments',icon:CircleDollarSign,color:'#30D158'},{label:'Current MRR',value:money(model.mrr),sub:`${model.active.length} active clients`,icon:WalletCards,color:'#64D2FF'},{label:'Projected annual',value:money(model.mrr*12),sub:'Current MRR × 12',icon:TrendingUp,color:'#BF5AF2'}];
  const chartFinance = model.breakdown.map(c=>({name:c.name?.split(' ')[0],revenue:Number(c.monthlyFee)||0,cost:c.cost}));
  const pie = [{name:'Collected',value:model.collection,color:'#30D158'},{name:'Outstanding',value:100-model.collection,color:'#FF9F0A'}];
  const markPaid = payment => paymentMutation.mutate({ action:'update', id:payment.id, data:{status:'PAID',paidDate:new Date().toISOString().slice(0,10)} });
  return <section className="agency-enter"><PageHeader title="Money" description="Live financials derived from Clients, Payments, and Team Members."/>
    <div className="grid gap-4 md:grid-cols-3">{cards.map(({icon:Icon,...card})=><div key={card.label} className="agency-glass rounded-2xl p-5"><div className="flex items-start justify-between"><div><p className="text-sm text-agency-muted">{card.label}</p><p className="mt-3 text-3xl font-semibold tracking-tight text-agency-primary">{card.value}</p><p className="mt-2 text-xs text-agency-muted">{card.sub}</p></div><span className="rounded-xl p-2.5" style={{color:card.color,background:`${card.color}18`}}><Icon className="h-5 w-5"/></span></div></div>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-3"><article className="agency-glass rounded-2xl p-5 xl:col-span-2"><h2 className="font-semibold text-agency-primary">MRR growth</h2><p className="mt-1 text-xs text-agency-muted">Based on active client start dates and current monthly fees.</p><div className="mt-5 h-64">{model.months.length ? <ResponsiveContainer width="100%" height="100%"><AreaChart data={model.months}><defs><linearGradient id="mrrFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#64D2FF" stopOpacity={.35}/><stop offset="1" stopColor="#64D2FF" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="name" stroke="#86868b" fontSize={11} tickLine={false} axisLine={false}/><YAxis stroke="#86868b" fontSize={11} tickFormatter={v=>`$${v/1000}k`} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={v=>money(v)}/><Area type="monotone" dataKey="mrr" stroke="#64D2FF" fill="url(#mrrFill)" strokeWidth={2}/></AreaChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-center text-sm text-agency-muted">Add client start dates to display real MRR history.</div>}</div></article>
      <article className="agency-glass rounded-2xl p-5"><h2 className="font-semibold text-agency-primary">Collection rate</h2><p className="mt-1 text-xs text-agency-muted">Paid versus all tracked payments.</p><div className="relative mt-3 h-56"><ResponsiveContainer><PieChart><Pie data={pie} dataKey="value" innerRadius={68} outerRadius={90} startAngle={90} endAngle={-270} stroke="none">{pie.map(entry=><Cell key={entry.name} fill={entry.color}/>)}</Pie></PieChart></ResponsiveContainer><div className="pointer-events-none absolute inset-0 flex items-center justify-center"><div className="text-center"><p className="text-3xl font-semibold text-agency-primary">{model.collection}%</p><p className="text-xs text-agency-muted">collected</p></div></div></div></article></div>
    <article className="agency-glass mt-5 overflow-hidden rounded-2xl"><div className="p-5"><h2 className="font-semibold text-agency-primary">MRR breakdown</h2></div><div className="overflow-x-auto"><table className="agency-table"><thead><tr><th>Client</th><th>Plan</th><th>Monthly fee</th><th>Setup fee</th><th>Team cost</th><th>Monthly profit</th></tr></thead><tbody>{model.breakdown.map(c=><tr key={c.id}><td className="font-medium text-agency-primary">{c.name}</td><td>{c.planType==='CUSTOM' ? c.customPlanLabel || 'Custom' : labelize(c.planType)}</td><td>{money(c.monthlyFee)}</td><td><span className={`agency-status ${c.setupPaid?'green':'orange'}`}>{c.setupPaid?'Paid':'Outstanding'}</span></td><td>{money(c.cost)}</td><td className={c.profit>=0?'text-[#30D158]':'text-[#FF453A]'}>{money(c.profit)}</td></tr>)}{!model.breakdown.length&&<tr><td colSpan={6} className="text-center">No active clients.</td></tr>}</tbody></table></div></article>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><article className="agency-glass rounded-2xl p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-agency-primary">Revenue vs costs</h2><p className="mt-1 text-xs text-agency-muted">Overall profit {money(model.profit)}/mo</p></div></div><div className="mt-5 h-72"><ResponsiveContainer><BarChart data={chartFinance}><CartesianGrid stroke="rgba(255,255,255,.06)" vertical={false}/><XAxis dataKey="name" stroke="#86868b" fontSize={11} tickLine={false} axisLine={false}/><YAxis stroke="#86868b" fontSize={11} tickFormatter={v=>`$${v/1000}k`} tickLine={false} axisLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={v=>money(v)}/><Bar dataKey="revenue" fill="#30D158" radius={[5,5,0,0]}/><Bar dataKey="cost" fill="#FF9F0A" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></article>
      <article className="agency-glass overflow-hidden rounded-2xl"><div className="p-5"><h2 className="font-semibold text-agency-primary">Payment tracker</h2></div><div className="max-h-[340px] overflow-auto agency-scrollbar"><table className="agency-table"><thead><tr><th>Client</th><th>Amount</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{model.trackedPayments.map(p=>{const client=clients.data.find(c=>c.id===p.client); return <tr key={p.id}><td>{client?.name||'Unknown client'}</td><td>{money(p.amount)}</td><td>{shortDate(p.dueDate)}</td><td><span className={`agency-status ${p.displayStatus==='PAID'?'green':p.displayStatus==='OVERDUE'?'red':'orange'}`}>{labelize(p.displayStatus)}</span></td><td>{p.displayStatus!=='PAID'&&<button className="agency-mark-paid" onClick={()=>markPaid(p)}><CheckCircle2/>Mark paid</button>}</td></tr>})}{!model.trackedPayments.length&&<tr><td colSpan={5} className="text-center">No payments recorded.</td></tr>}</tbody></table></div></article></div>
  </section>;
}
